matrix:
  include:
    # - language: python
    #   python: 
    #     - 3.4
    #   before_install:
    #     - cd backend/
    #   install: 
    #     - pip install -r requirements.txt
    #   script:
    #     - python manage.py test

    - language: node_js
      node_js:
        - 10
      before_install:
        - git clone https://github.com/apple/sourcekit-lsp.git
        - npm install -g vsce
        - cd sourcekit-lsp/Editors/vscode
      install:
        - yarn install
        - yarn postinstall
      script:
        - vsce package
      deploy:
        provider: releases
        api_key: $TOKEN
        file: sourcekit-lsp-0.0.1.vsix
        skip_cleanup: true
        on:
          tags: false