matrix:
  include:
      os: linux
      language: generic
      sudo: required
      before_install:
        - git clone https://github.com/apple/sourcekit-lsp.git
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - cd sourcekit-lsp
      install:
        - npm install
        - npm run postinstall
      script:
        - vsce package
      deploy:
        provider: releases
        api_key: $TOKEN
        file: sourcekit-lsp-0.0.1.vsix
        skip_cleanup: true
        on:
          tags: true

    - language: node_js
      node_js:
        - 10
      before_install:
        - git clone https://github.com/apple/sourcekit-lsp.git
        - npm install -g vsce
        - cd sourcekit-lsp/Editors/vscode
      install:
        - npm install
        - npm run postinstall
      script:
        - vsce package
      deploy:
        provider: releases
        api_key: $TOKEN
        file: sourcekit-lsp-0.0.1.vsix
        skip_cleanup: true
        on:
          tags: true