matrix:
  include:
    - language: generic
      sudo: required
      before_install:
        - apt-get -q update
        - apt-get -q install -y sqlite3 libsqlite3-dev libblocksruntime-dev
        - git clone https://github.com/apple/sourcekit-lsp.git
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - cd sourcekit-lsp
      install:
        - swiftenv install 5.0.1
        - swift --version
        - swiftenv which swift
      script:
        - swift build -Xcxx -I/home/travis/.swiftenv/versions/5.0.1/usr/bin/swift && mv `swift build --show-bin-path`/sourcekit-lsp /releases
      deploy:
        provider: releases
        api_key: $TOKEN
        file_glob: true
        file: releases/**/*
        skip_cleanup: true
        on:
          tags: true

    - language: node_js
      node_js:
        - 10
      before_install:
        - git clone https://github.com/apple/sourcekit-lsp.git
        - npm install -g vsce
        - cd sourcekit-lsp/Editors/vscode
      install:
        - npm install
        - npm run postinstall
      script:
        - vsce package
      deploy:
        provider: releases
        api_key: $TOKEN
        file: sourcekit-lsp-0.0.1.vsix
        skip_cleanup: true
        on:
          tags: true