matrix:
  include:
    - language: generic
      sudo: required
      before_install:
        - git clone https://github.com/apple/sourcekit-lsp.git
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - cd sourcekit-lsp
      install:
        - swift --version
        - swiftenv which swift
      script:
        - swift build -Xcxx -I/usr/lib/swift && mv `swift build --show-bin-path`/sourcekit-lsp /usr/bin/
      deploy:
        provider: releases
        api_key: $TOKEN
        file_glob: true
        file: sourcekit-lsp-0.0.1.vsix
        skip_cleanup: true
        on:
          tags: true

    - language: node_js
      node_js:
        - 10
      before_install:
        - git clone https://github.com/apple/sourcekit-lsp.git
        - npm install -g vsce
        - cd sourcekit-lsp/Editors/vscode
      install:
        - npm install
        - npm run postinstall
      script:
        - vsce package
      deploy:
        provider: releases
        api_key: $TOKEN
        file: sourcekit-lsp-0.0.1.vsix
        skip_cleanup: true
        on:
          tags: true